analysis:
  stage: analysis
  script:
  - bash ci.sh analysis

before_script:
- export BUILD_SITE=true
#- export LIB_CI_SCRIPT=https://github.com/home1-oss/oss-build/raw/master/src/main/ci-script/lib_ci.sh
- export LIB_CI_SCRIPT=${CI_PROJECT_URL}/raw/${CI_COMMIT_REF_NAME}/src/main/ci-script/lib_ci.sh
- export ORIGIN_REPO_SLUG=home1-oss/oss-build

on_develop_push:
  dependencies:
  - on_non_release_push
  only:
  - develop
  script:
  - bash ci.sh publish_artifact publish_site
  stage: publish

#on_master_push:
#  dependencies:
#  - on_non_release_push
#  only:
#  - master
#  script:
#  - echo do nothing
#  stage: publish

on_non_release_push:
  artifacts:
    expire_in: 1 day
    untracked: true
  except:
  - /^release\/.+$/
  script:
  - bash ci.sh clean test_and_build
  stage: build

on_release_push:
#  artifacts:
#    paths:
#    - "**/target/pom.xml"
  only:
  - /^release\/.+$/
  script:
  - bash ci.sh clean test_and_build publish_artifact publish_site
  stage: publish

stages:
- analysis
- build
- publish

# see: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/ci/yaml/README.md
# see: https://gitlab.com/gitlab-org/gitlab-ce/issues/3423
