before_script:
- export BUILD_SITE=true
#- export LIB_CI_SCRIPT=https://github.com/home1-oss/oss-build/raw/develop/src/main/ci-script/lib_ci.sh
- export LIB_CI_SCRIPT=http://gitlab.local:10080/home1-oss/oss-build/raw/develop/src/main/ci-script/lib_ci.sh
- export ORIGIN_REPO_SLUG=home1-oss/oss-build

stages:
- analysis
- test_and_build
- deploy

sonar:
  stage: analysis
  script:
  - bash ci.sh analysis

on_develop_push:
  dependencies:
  - on_every_push
  only:
  - develop
  script:
  - bash ci.sh publish_artifact publish_site
  stage: deploy

on_every_push:
#  artifacts:
#    expire_in: 1 day
#    untracked: true
  script:
  - bash ci.sh test_and_build
  stage: test_and_build

#on_master_push:
#  dependencies:
#  - on_every_push
#  only:
#  - master
#  script:
#  - echo do nothing
#  stage: deploy

on_release_push:
#  artifacts:
#    paths:
#    - "**/target/pom.xml"
  dependencies:
  - on_every_push
  only:
  - /^release\/.+$/
  script:
  - bash ci.sh publish_artifact publish_site
  stage: deploy
